import {
	DownloadSearchKeywordPreset,
	DownloadSearchProvider,
} from "../types/download-search";

export const BUILT_IN_DOWNLOAD_SEARCH_PROVIDERS: DownloadSearchProvider[] = [
	{
		id:        "nyaa",
		label:     "Nyaa.si",
		category:  "torrent",
		baseUrl: "https://nyaa.si/?f=0&c=0_0&q={query}",
		isBuiltIn: true,
		enabled:   true,
		sortOrder: 0,
	},
	{
		id:        "tokyo-toshokan",
		label:     "Tokyo Toshokan",
		category:  "torrent",
		baseUrl: "https://www.tokyotosho.info/search.php?terms={query}",
		isBuiltIn: true,
		enabled:   true,
		sortOrder: 1,
	},
	{
		id:        "anidex",
		label:     "AniDex",
		category:  "torrent",
		baseUrl: "https://anidex.moe/?q={query}",
		isBuiltIn: true,
		enabled:   true,
		sortOrder: 2,
	},
	{
		id:        "1337x",
		label:     "1337x",
		category:  "index",
		baseUrl:   "https://1337x.to/search/{query}/1/",
		isBuiltIn: true,
		enabled:   true,
		sortOrder: 3,
	},
	{
		id:        "the-pirate-bay",
		label:     "The Pirate Bay",
		category:  "index",
		baseUrl: "https://thepiratebay.org/search.php?q={query}",
		isBuiltIn: true,
		enabled:   true,
		sortOrder: 4,
	},
];

export const BUILT_IN_DOWNLOAD_SEARCH_KEYWORD_PRESETS: DownloadSearchKeywordPreset[] = [
	...[
		"480p",
		"720p",
		"1080p",
		"2160p",
		"4K",
		"batch",
	].map((value) => ({
		id:        `quality-${ value.toLowerCase() }`,
		label:     value,
		value,
		category:  "quality" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
	...[
		"WEB-DL",
		"WEBRip",
		"BluRay",
		"BDRip",
		"DVD",
		"HDTV",
	].map((value) => ({
		id:        `source-${ value.toLowerCase() }`,
		label:     value,
		value,
		category:  "source" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
	...[
		"x264",
		"x265",
		"HEVC",
		"AV1",
	].map((value) => ({
		id:        `format-${ value.toLowerCase() }`,
		label:     value,
		value,
		category:  "format" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
	...[
		"sub",
		"dub",
		"dual audio",
		"multi subs",
		"English subs",
	].map((value) => ({
		id: `subtitles-${ value.toLowerCase().replace(
			/\s+/g,
			"-",
		) }`,
		label:     value,
		value,
		category:  "subtitles" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
	...[
		"AAC",
		"FLAC",
		"Opus",
		"5.1",
	].map((value) => ({
		id:        `audio-${ value.toLowerCase() }`,
		label:     value,
		value,
		category:  "audio" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
	...[
		"Complete",
		"season",
	].map((value) => ({
		id:        `completion-${ value.toLowerCase() }`,
		label:     value,
		value,
		category:  "completion" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
	...[
		"SubsPlease",
		"Erai-raws",
		"EMBER",
		"Judas",
		"ASW",
		"Yameii",
		"Golumpa",
	].map((value) => ({
		id:        `origin-${ value.toLowerCase() }`,
		label:     value,
		value,
		category:  "origin" as const,
		isBuiltIn: true,
		enabled:   true,
	})),
];
