// Compatibility barrel for catalog, hydration, integration, and user-state DTOs.
// Domain-specific modules own the contracts; this stable path avoids a broad
// import migration for existing consumers and must not acquire domain logic.
export type {
	AnimeDbMediaIngestionSource,
	AnimeDbReadinessFactsDto,
	CatalogMediaIngestedEvent,
	CharacterDto,
	EpisodeDetailsSnapshotDto,
	EpisodeDto,
	EpisodeProviderMappingDto,
	GenreDto,
	GroupBlueprintDto,
	GroupDto,
	GroupLineageDto,
	GroupLineageProviderMappingDto,
	GroupMediaDto,
	GroupMediaLinkDto,
	MediaCharacterDto,
	MediaCoverImageParsedJson,
	MediaDetailsSnapshotDto,
	MediaDto,
	MediaGenreDto,
	MediaImageGallerySourceDto,
	MediaImagePreviewDto,
	MediaProviderIdsDto,
	MediaProviderMappingDto,
	MediaRelationCanonicalDto,
	MediaRelationDto,
	MediaTagDto,
	TagDto,
} from "./anime-db-catalog";
export type {
	ActiveImageSelectionDto,
	CachedImageEntryDto,
	CachedImageStatus,
	DisplayImageOrientation,
	ImageCandidateSourceKind,
	ImageGalleryRole,
	ImageOwnerKind,
	ImageRole,
	ResolvedDisplayImageDto,
	ResolvedImageSource,
	UserLocalImageEntryDto,
	UserUploadedImageEntryDto,
} from "./anime-db-images";
export type {
	IntegrationStatus,
	PlaybackIssueCategory,
} from "./anime-db-integration";
export type {
	GroupLineageProviderMappingType,
	ProviderMappingConfidence,
	ProviderName,
} from "./anime-db-provider";
export type {
	AniListInsertErrorLogDto,
	AnimeDbScanStateDto,
	JikanEpisodesCoverageStatus,
	JikanEpisodesSyncStateDto,
	MediaAdHocRefreshFactsDto,
	MediaCharactersQueueDto,
	MediaEpisodeUpdatesIssueReason,
	MediaEpisodeUpdatesSupportFactsDto,
	MediaJikanEpisodeThumbnailsQueueDto,
	MediaJikanEpisodesQueueDto,
	MediaStaffQueueDto,
} from "./anime-db-hydration";
export type {
	CreateMergedUserGroupResultDto,
	GroupingMutationImpactDto,
	IntegrationCascadeResultDto,
	ReleaseWatchMediaFactsDto,
	RestoreUserGroupLineageResultDto,
	MediaGroupSummaryDto,
	UserEpisodeIntegrationSnapshotDto,
	UserEpisodeIntegrationSnapshotRowDto,
	UserEpisodeOverrideDto,
	UserEpisodeOverrideRowDto,
	UserEpisodePlaybackIssueMomentDto,
	UserEpisodePlaybackIssueMomentRowDto,
	UserEpisodeStateDto,
	UserEpisodeStateRowDto,
	UserGroupBlueprintDto,
	UserGroupIntegrationSnapshotRowDto,
	UserGroupLineageDto,
	UserGroupLineageRowDto,
	UserGroupLineageStatus,
	UserGroupMediaDto,
	UserGroupMediaLinkDto,
	UserGroupOverrideDto,
	UserGroupingMode,
	UserGroupingStateDto,
	UserGroupRowDto,
	UserGroupStateRowDto,
	UserMediaIntegrationSnapshotRowDto,
	UserMediaOverrideRowDto,
	UserMediaPlaybackIssueMomentRowDto,
	UserMediaStateRowDto,
	UserReleaseWatchStateDto,
	UserScheduledMediaRefreshDto,
} from "./anime-db-user-state";
export type {
	AnimeDbReconcileSafetyDiagnosticsDto,
	ReconcileApplyExecutionResult,
	ReconcileApplySummary,
	ReconcileApplySummaryReport,
	ReconcileConflictAutoApplyBehavior,
	ReconcileConflictHandlingGuidance,
	ReconcileConflictReason,
	ReconcileConflictRecommendedAction,
	ReconcileConflictRecordPayload,
	ReconcileLineageClass,
	ReconcileLineageItem,
	ReconcilePreflightReport,
	ReconcilePreflightSummary,
	ReconcilePreflightSummaryReport,
	ReconcileRunStatus,
	UserGroupingDiagnosticsCountsDto,
	UserGroupingDiagnosticsDto,
	UserGroupingDiagnosticsIssueCountsDto,
	UserGroupingLatestReconcileRunDto,
} from "./anime-db-reconcile";
