// Compatibility barrel for IPC payload contracts shared between main and preload/renderer.
// Domain files keep transport boundaries readable while this path stays stable for existing consumers.
export type {
	AnimeDbDownloadActionResult,
	AnimeDbDownloadProgressData,
	AnimeDbDownloadReleaseStatus,
	AnimeDbPopulationActionResult,
	AnimeDbStartupReadiness,
	AnimeDbUpdateActionResult,
	AnimeDbUpdateProgressData,
	PopulateAnimeDbProgressData,
} from "./ipc-anime-db-payloads";
export type {
	DeleteMediaImageGalleryImageRequest,
	EpisodeImageGalleryData,
	GroupImageGalleryData,
	ImageGalleryCandidate,
	ImageGallerySelectionInput,
	ImageGalleryTab,
	MediaImageGalleryData,
	SaveEpisodeEditRequest,
	SaveEpisodeImageGalleryRequest,
	SaveGroupEditRequest,
	SaveGroupImageGalleryRequest,
	SaveImageGalleryActionResult,
	SaveMediaEditRequest,
	SaveMediaImageGalleryRequest,
	UploadEpisodeImageGalleryImageRequest,
	UploadGroupImageGalleryImageRequest,
	UploadImageGalleryImageActionResult,
	UploadMediaImageGalleryImageRequest,
} from "./ipc-image-gallery-payloads";
export type {
	GroupCreateFromSelectionActionResult,
	GroupImageSelectionResult,
	GroupManualAssignLibrarySelectionRequest,
	GroupManualAssignMediasRequest,
	GroupManualCreateGroupFromLibrarySelectionRequest,
	GroupManualCreateMergedGroupFromLibrarySelectionRequest,
	GroupManualDeleteRequest,
	GroupManualMergeLibrarySelectionRequest,
	GroupManualMergeRequest,
	GroupManualRemoveMediaRequest,
	GroupMediaAssignmentActionResult,
	GroupMutationActionResult,
	GroupRefreshActionResult,
	GroupRestoreDeletedLineageActionResult,
	GroupRestoreDeletedLineageRequest,
	GroupUpdateDetailsActionResult,
	LibrarySelectionInput,
	UpdateGroupDetailsRequest,
} from "./ipc-group-mutation-payloads";
export type {
	EpisodeUpdateDetailsActionResult,
	MediaRefreshActionResult,
	MediaUpdateDetailsActionResult,
	ResetEpisodeDetailsRequest,
	ResetMediaDetailsRequest,
	UpdateEpisodeDetailsRequest,
	UpdateMediaDetailsRequest,
} from "./ipc-media-edit-payloads";
export type {
	EpisodePlaybackIssueMoment,
	IntegrationStatusActionResult,
	MediaWatchStateActionResult,
	SaveEpisodeIntegrationStateRequest,
	SaveMediaIntegrationStateRequest,
	SetEpisodeIntegrationStatusesRequest,
	SetEpisodeIntegrationStatusRequest,
	SetEpisodeWatchStatesRequest,
	SetEpisodeWatchStateRequest,
	SetGroupIntegrationStatusRequest,
	SetGroupWatchStateRequest,
	SetMediaIntegrationStatusRequest,
	SetMediaWatchStateRequest,
} from "./ipc-integration-payloads";
export type {
	GroupExplorerCard,
	GroupExplorerCardsPage,
	GroupListChangedEvent,
	LibraryDisplayItem,
	LibraryDisplayItemsPage,
	LibraryDisplayItemsRange,
	LibraryDisplayItemsRangeRequest,
	LibraryDisplayScope,
	LibraryFilterOptions,
} from "./ipc-library-payloads";
export type {
	RendererImageFetchRequest,
	RendererImageFetchResponse,
	RendererLocalImageFetchRequest,
} from "./ipc-renderer-image-payloads";
export type {
	GroupInspectionMediaCard,
	GroupInspectionSummary,
	GroupMediaItemsPatchedEvent,
	GroupMediaListChangedEvent,
	GroupMediaWallRange,
	GroupMediaWallRangeRequest,
} from "./ipc-group-inspection-payloads";
export type {
	MediaEpisodeInspectionRow,
	MediaEpisodesItemsPatchedEvent,
	MediaEpisodesListChangedEvent,
	MediaEpisodeUpdatesIssue,
	MediaInspectionData,
	MediaInspectionGroupCard,
	MediaInspectionOptions,
	MediaNextAiringEpisodeSummary,
	MediaTagSummary,
	RetryMediaEpisodeUpdatesResult,
} from "./ipc-media-inspection-payloads";
export type {
	CharacterInspectionData,
	CharacterMediaCard,
	CharacterVoiceActorCredit,
	CharacterVoiceActorMediaCredit,
	MediaCharacterListItem,
	MediaCharacterVoiceActor,
	MediaStaffListItem,
	StaffInspectionData,
	StaffMediaCreditCard,
	VoiceActorCharacterMediaCard,
	VoiceActorInspectionData,
} from "./ipc-people-payloads";
export type {
	ReconcileApplyActionResult,
	ReconcilePreflightActionResult,
} from "./ipc-reconcile-payloads";
export type {
	ErroredContentItem,
	ErroredContentPage,
	ErroredContentQueue,
	ErroredContentQueueStatus,
	ErroredContentRecommendedAction,
	HideErroredContentRequest,
	HideErroredContentResult,
	HydratorProgressEvent,
	HydratorProgressQueue,
	HydratorProgressStatus,
	ReportErroredContentRequest,
	ReportErroredContentResult,
	RetryAllErroredContentRequest,
	RetryAllErroredContentResult,
	RetryErroredContentRequest,
	RetryErroredContentResult,
} from "./ipc-hydrator-payloads";
export type {
	LibraryAdultFilter,
	LibraryDisplayFilters,
	LibraryDisplayMode,
} from "./user-config";
